# Site settings
title: KEVIN MANSFIELD Research explorations in lighting
email: kevin.mansfield@ucl.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  An Open Notebook exploring light and lighting research.
baseurl: 
url: http://kpmansfield.github.io
twitter_username: mansfieldkp
github_username:  kpmansfield

# Build settings
markdown: kramdown
    
remote_theme: pages-themes/minimal@v0.2.0
plugins: - jekyll-remote-theme
