# Site settings
title: Kevin Mansfield     <span style="color:rgb(190,80,30); font-family:Optima;">Research explorations in lighting</span>
email: kevin.mansfield@ucl.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  An Open Notebook exploring light and lighting research.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: mansfieldkp
github_username:  kpmansfield

# Build settings
markdown: kramdown
